site_name: 我的文档
site_url: https://hicaosen.github.io/docs/
theme: readthedocs
repo_name: hicaosen/docs
repo_url: https://github.com/hicaosen/docs

nav:
    - 首页: index.md
    - 备忘录: todolist.md
    - Java:
      - Java基础: java-basics.md
      - Java反射: java-reflection.md
      - StringBuffer和StringBuilder区别: StringBuffer-StringBuilder-diff.md
    - Git:
      - Git基础: git-basics.md
